name: Build and Deploy Web

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
            version: 1.38.40
            actions-cache-folder: 'emsdk-cache'

      - name: Build Web
        run: |
          make web

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
